# Generated by Django 3.2.8 on 2021-11-28 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigoCli', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('nomUsuario', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=12)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('numeroDocumento', models.CharField(max_length=21, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes')),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('colorID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('dimensionID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estadoID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('estiloID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marcaID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('tarjetaID', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjeta', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
                ('mmaa', models.CharField(max_length=10)),
                ('codigoCli', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipoDocID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('tipoProID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tipoproductos')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjetaID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoPro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precioMayor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('talla', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('colorID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.color')),
                ('dimensionID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.dimension')),
                ('estiloID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.estilo')),
                ('marcaID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.marca')),
                ('tipoProID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleVentaID', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('codigoPro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.producto')),
                ('ventaID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentarioID', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=300)),
                ('usuario', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('codigoPro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_comentarios', to='administrador.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoDocID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tipodocumento'),
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('carritoID', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('datos_payu', models.CharField(blank=True, max_length=700, null=True)),
                ('comprado', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_carrito', to='administrador.producto')),
                ('usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
