# Generated by Django 3.2 on 2021-10-23 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigoCli', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('nomUsuario', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('numeroDocumento', models.CharField(max_length=21, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('colorID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('dimensionID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estadoID', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('estiloID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventarioID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marcaID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('tarjetaID', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjeta', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
                ('mmaa', models.CharField(max_length=10)),
                ('codigoCli', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipoDocID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('tipoProID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tipoproductos')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjetaID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoPro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precioMayor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('talla', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('colorID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.color')),
                ('dimensionID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.dimension')),
                ('estiloID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.estilo')),
                ('marcaID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.marca')),
                ('tipoProID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleVentaID', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('codigoPro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.producto')),
                ('ventaID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('detalleInventarioID', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.IntegerField()),
                ('cantidad_reposicion', models.IntegerField(default=0)),
                ('cantidad_defectuoso', models.IntegerField(default=0)),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('codigoPro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.producto')),
                ('estadoID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.estado')),
                ('inventarioID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.inventario')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoDocID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tipodocumento'),
        ),
    ]
