# Generated by Django 3.2.8 on 2021-11-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='datos_payu',
        ),
    ]
