# Generated by Django 3.2.8 on 2021-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_carritocompras_datos_payu'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='cuenta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='cvv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
