# Generated by Django 3.2.8 on 2021-12-01 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0003_auto_20211129_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='codigoPro',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='ventaID',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='codigoCli',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='igv',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tarjetaID',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='ventaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='costoEnvio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccionEnvio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='mmaa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='numeroTarjeta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venta_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
