# Generated by Django 3.2.8 on 2021-12-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20211201_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
