# Generated by Django 3.2.8 on 2021-12-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_carritocompras_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nomUsuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='mmaa',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numeroTarjeta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mmaa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numeroTarjeta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
