# Generated by Django 3.2.8 on 2021-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referenciaDireccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
