# Generated by Django 3.2.8 on 2021-12-03 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0009_auto_20211202_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('mensajeID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('remitente', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=500, null=True)),
                ('destinatario', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensaje_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
