# Generated by Django 3.2.8 on 2021-12-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_auto_20211203_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
