# Generated by Django 3.2.8 on 2021-11-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigoCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('nomUsuario', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=12)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('numeroDocumento', models.CharField(max_length=21, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
