# Generated by Django 3.2.8 on 2021-11-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigoCursp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.curso'),
        ),
    ]
