# Generated by Django 3.2 on 2021-10-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='articulos'),
        ),
    ]
