# Generated by Django 3.2 on 2021-10-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('tipoProId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField()),
                ('marca', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('talla', models.IntegerField()),
                ('tipoPro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='administrador.tipoproducto')),
            ],
        ),
    ]
